### ISSUE TITLE
How about add BN after each expanded Conv layer

### ISSUE THREAD

**Issue by pansiyuan123** [GUOShuxuan/expandnets#2]
Very interesting work! I'm curious why not add BN after each extended CONV layer. I don't know if it can bring improvement.

**Comment by GUOShuxuan** [comment]
Hi, we have tried to add BN, however, in most cases, it didn't help, even got slightly worse results than without bn.

**Comment by GUOShuxuan** [comment]
> Very interesting work! I'm curious why not add BN after each extended CONV layer. I don't know if it can bring improvement.

Hi, we have tried to add BN, however, in most cases, it didn't help, even got slightly worse results than without bn.
