### ISSUE TITLE
About padding

### ISSUE THREAD

**Issue by OOLLcnm** [GUOShuxuan/expandnets#4]
Hello, your work is great.
I noticed that the padding operation is used in 1x1 convolution, but it's usually used in 3x3 convolution and I would like to know why.

**Comment by GUOShuxuan** [comment]
> Hello, your work is great.
> I noticed that the padding operation is used in 1x1 convolution, but it's usually used in 3x3 convolution and I would like to know why.

Hi, we have to make sure the input (including padding) for the expand units is same as the original one. Thus we should use padding in the first 1*1 conv layer.
